version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install all dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  unit_tests:
    docker:
      - image: circleci/node:10.0.0    
    steps:
      - checkout
      - setup_remote_docker

      - run:
        name: Install Docker client
        command: |
          set -x
          VER="17.03.0-ce"
          curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          mv /tmp/docker/* /usr/bin
      - run:
          name: Compose up
          command: docker-compose up
      - run: 
          name: Unit tests
          command: yarn unit 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit_tests:
        requires:
          - build
                    
