version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker: 
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  unit_tests:
    working_directory: ~/repo
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run: 
          name: unit tests
          command: yarn unit 

  functionnal_tests:
    working_directory: ~/repo
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Compose up
          command: docker-compose up -d
      - run:
          name: Execute database migrations
          command: docker-compose exec server node migrations.js up
      - run:
          name: e2e tests
          command: yarn e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
      - functionnal_tests:
          requires:
            - build
                    
