version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker: 
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install all dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  unit_tests:
    working_directory: ~/repo
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout

      - run: 
          name: Unit tests
          command: yarn unit 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
                    
